# Generated by Django 5.0.4 on 2024-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='third_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
    ]
