# Generated by Django 5.0.4 on 2024-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_name_user_first_name_user_second_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default='', max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
