# Generated by Django 5.0.4 on 2024-05-06 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_permission_alter_user_second_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 19, 40, 7, 230479), verbose_name='Дата рождения'),
        ),
    ]
